import { describe, it, expect } from 'vitest';
import {
    detectFormat,
    GeneticParseError,
    parseGeneticFile,
} from '../parsers';

// ─── Synthetic fixtures ──────────────────────────────────────────────────────
//
// 200 rows so we clear the parser's >=100-variant sanity guard, while
// keeping the fixture small enough to read inline. We assemble bodies
// programmatically rather than copy-paste so the test stays readable.

function rows23(n: number): string {
    const out: string[] = [];
    for (let i = 0; i < n; i++) {
        const chr = (i % 22) + 1;
        out.push(`rs${1000 + i}\t${chr}\t${100000 + i * 13}\tAG`);
    }
    return out.join('\n');
}

function rowsAncestry(n: number): string {
    const out: string[] = [];
    for (let i = 0; i < n; i++) {
        const chr = (i % 22) + 1;
        // Ancestry splits the genotype across two columns.
        out.push(`rs${2000 + i}\t${chr}\t${200000 + i * 17}\tA\tG`);
    }
    return out.join('\n');
}

function rowsMyHeritage(n: number): string {
    const out: string[] = [];
    for (let i = 0; i < n; i++) {
        const chr = (i % 22) + 1;
        out.push(`"rs${3000 + i}","${chr}","${300000 + i * 19}","CC"`);
    }
    return out.join('\n');
}

const HEADER_23ANDME = `# This file was generated by 23andMe at: 2026-01-15 00:00:00 UTC
# This data file contains raw genotype data from 23andMe v5 chip.
# rsid\tchromosome\tposition\tgenotype
`;

const HEADER_ANCESTRY = `#AncestryDNA raw data download
# Generated 2026-01-15
# rsid\tchromosome\tposition\tallele1\tallele2
`;

const HEADER_MYHERITAGE = `# MyHeritage raw DNA data download
"RSID","CHROMOSOME","POSITION","RESULT"
`;

const HEADER_FAMILYTREE = `# FamilyTreeDNA FamilyFinder raw data
"RSID","CHROMOSOME","POSITION","RESULT"
`;

// ─── detectFormat ────────────────────────────────────────────────────────────

describe('detectFormat', () => {
    it('identifies 23andMe by header signature', () => {
        expect(detectFormat(HEADER_23ANDME + rows23(5))).toBe('23andme');
    });

    it('identifies AncestryDNA by header signature', () => {
        expect(detectFormat(HEADER_ANCESTRY + rowsAncestry(5))).toBe('ancestrydna');
    });

    it('identifies MyHeritage by header signature', () => {
        expect(detectFormat(HEADER_MYHERITAGE + rowsMyHeritage(5))).toBe(
            'myheritage',
        );
    });

    it('identifies FamilyTreeDNA by header signature', () => {
        expect(
            detectFormat(HEADER_FAMILYTREE + rowsMyHeritage(5)),
        ).toBe('familytree');
    });

    it('identifies VCF by ##fileformat= line', () => {
        expect(detectFormat('##fileformat=VCFv4.3\n#CHROM\tPOS\n')).toBe('vcf');
    });

    it('falls back to 23andMe when only the bare header row is present', () => {
        expect(detectFormat('rsid\tchromosome\tposition\tgenotype\n' + rows23(5)))
            .toBe('23andme');
    });

    it('returns null for unrelated text', () => {
        expect(detectFormat('this is a normal text file')).toBeNull();
    });
});

// ─── parseGeneticFile: 23andMe ──────────────────────────────────────────────

describe('parseGeneticFile: 23andMe', () => {
    it('parses a clean 23andMe-shaped file', () => {
        const text = HEADER_23ANDME + rows23(200);
        const result = parseGeneticFile(text);

        expect(result.format).toBe('23andme');
        expect(result.chip_version).toBe('v5');
        expect(result.variants).toHaveLength(200);
        expect(result.clean).toBe(true);
        expect(result.skipped).toBe(0);

        const first = result.variants[0];
        expect(first.rsid).toBe('rs1000');
        expect(first.chromosome).toBe('1');
        expect(first.position).toBe(100000);
        expect(first.genotype).toBe('AG');
        expect(first.confidence).toBe('high');
    });

    it('normalizes the "--" no-call into a no_call confidence', () => {
        const body = rows23(199) + '\nrs9999\t3\t500000\t--';
        const result = parseGeneticFile(HEADER_23ANDME + body);
        const noCall = result.variants[result.variants.length - 1];
        expect(noCall.genotype).toBe('--');
        expect(noCall.confidence).toBe('no_call');
    });

    it('strips a UTF-8 BOM at the start of the file', () => {
        const text = '﻿' + HEADER_23ANDME + rows23(200);
        expect(() => parseGeneticFile(text)).not.toThrow();
    });

    it('normalizes "chr1" / "M" → "1" / "MT"', () => {
        const text =
            HEADER_23ANDME +
            rows23(199) +
            '\nrs7777\tchr1\t999\tAA\nrs8888\tM\t1\tAA';
        const result = parseGeneticFile(text);
        const lastTwo = result.variants.slice(-2);
        expect(lastTwo[0].chromosome).toBe('1');
        expect(lastTwo[1].chromosome).toBe('MT');
    });
});

// ─── parseGeneticFile: AncestryDNA ──────────────────────────────────────────

describe('parseGeneticFile: AncestryDNA', () => {
    it('reassembles the 5-column allele1/allele2 layout', () => {
        const text = HEADER_ANCESTRY + rowsAncestry(200);
        const result = parseGeneticFile(text);

        expect(result.format).toBe('ancestrydna');
        expect(result.variants).toHaveLength(200);
        expect(result.variants[0].genotype).toBe('AG');
    });
});

// ─── parseGeneticFile: MyHeritage / FamilyTreeDNA ───────────────────────────

describe('parseGeneticFile: MyHeritage', () => {
    it('parses the quoted CSV body', () => {
        const text = HEADER_MYHERITAGE + rowsMyHeritage(200);
        const result = parseGeneticFile(text);

        expect(result.format).toBe('myheritage');
        expect(result.variants).toHaveLength(200);
        expect(result.variants[0].rsid).toBe('rs3000');
        expect(result.variants[0].genotype).toBe('CC');
    });
});

describe('parseGeneticFile: FamilyTreeDNA', () => {
    it('parses the FamilyFinder CSV body', () => {
        const text = HEADER_FAMILYTREE + rowsMyHeritage(200);
        const result = parseGeneticFile(text);
        expect(result.format).toBe('familytree');
        expect(result.variants).toHaveLength(200);
    });
});

// ─── Error paths ─────────────────────────────────────────────────────────────

describe('parseGeneticFile: errors', () => {
    it('throws on empty input', () => {
        expect(() => parseGeneticFile('')).toThrow(GeneticParseError);
        expect(() => parseGeneticFile('   \n  \n')).toThrow(GeneticParseError);
    });

    it('throws on completely unrecognized content', () => {
        expect(() => parseGeneticFile('just a normal text file')).toThrow(
            GeneticParseError,
        );
    });

    it('throws when parsed variant count is below the 100-row sanity guard', () => {
        // Header is fine but only 5 body rows — clearly not a real export.
        expect(() =>
            parseGeneticFile(HEADER_23ANDME + rows23(5)),
        ).toThrow(/Parsed only/);
    });

    it('skips malformed rows but keeps going', () => {
        // 199 good rows + 1 garbage row → parser counts the skip.
        const body = rows23(199) + '\nGARBAGE LINE';
        const result = parseGeneticFile(HEADER_23ANDME + body);
        expect(result.variants).toHaveLength(199);
        expect(result.skipped).toBe(1);
        expect(result.clean).toBe(false);
    });
});
