import { Link } from 'react-router-dom';
import { ArrowLeft, Shield } from 'lucide-react';

/**
 * Privacy Policy — written against the app's actual data practices
 * (health-provider integrations, AI chat processing, Stripe billing,
 * family/legacy records, voice features). Serves both the in-app links
 * (Signup/Login/Landing) and the App Store Connect privacy-URL requirement.
 */
export default function PrivacyPolicy() {
  return (
    <LegalPage title="Privacy Policy" icon={<Shield className="h-6 w-6 text-teal-400" />} updated="July 12, 2026">
      <Section heading="Who we are">
        EverAfter AI (“EverAfter,” “we,” “us”) is a digital legacy and health companion platform
        operated by Wise &amp; Savvy LLC. This policy explains what we collect, why, and the choices
        you have. It applies to everafterai.net and our mobile applications.
      </Section>

      <Section heading="Information we collect">
        <ul className="list-disc space-y-2 pl-5">
          <li><strong className="text-slate-200">Account information</strong> — email address and authentication credentials, managed by our infrastructure provider Supabase.</li>
          <li><strong className="text-slate-200">Health and wellness data</strong> — only when you connect a provider or enter it yourself: heart rate, sleep, activity, glucose, and related metrics from services you authorize (such as Terra, Fitbit, Oura, Dexcom, or Withings), plus medications, appointments, goals, and vitals you log.</li>
          <li><strong className="text-slate-200">Family and legacy content</strong> — family-tree records, memories, stories, photos, voice recordings, letters, time capsules, ceremonies, and vault items you create, including material intended for release to people you designate.</li>
          <li><strong className="text-slate-200">Personality training responses</strong> — answers to daily and quiz questions used to build the AI personalities (“engrams”) you create.</li>
          <li><strong className="text-slate-200">Financial information you provide</strong> — budgets, transactions, and (if you link a bank through Plaid) account and transaction summaries. Payment card details are collected and processed by Stripe, not stored by us.</li>
          <li><strong className="text-slate-200">Technical basics</strong> — log and device information needed to run and secure the service. We do not use third-party advertising or analytics trackers.</li>
        </ul>
      </Section>

      <Section heading="How we use it">
        We use your information to run the features you ask for: showing your health dashboards,
        generating AI companion responses, building the engrams you train, coordinating family
        features, processing subscriptions, and safeguarding legacy content for the recipients you
        choose. AI chat responses are generated by third-party model providers acting as our
        processors; your conversations are not used by us to advertise to you, and we do not sell
        your personal information.
      </Section>

      <Section heading="What EverAfter is not">
        EverAfter's health features are for general wellness awareness. They are not medical
        advice, diagnosis, or treatment, and the service is not a medical device. Always consult a
        qualified clinician about medical questions, and call your local emergency number in an
        emergency.
      </Section>

      <Section heading="Sharing">
        We share personal information only with: (1) service providers who process it for us —
        Supabase (hosting, database, authentication), Render (application hosting), Netlify (web
        hosting), Stripe (payments), Plaid (bank connections you initiate), health-data aggregators
        you connect (such as Terra or Dexcom), AI model providers used to generate responses, and
        voice-synthesis providers for voice features you use; (2) people you explicitly designate —
        family members, beneficiaries, or legacy recipients, under the access rules you set; and
        (3) authorities when the law requires it. We do not sell or rent personal information.
      </Section>

      <Section heading="Retention and deletion">
        We keep your information while your account is active or as needed for the legacy releases
        you have configured. You can delete individual items in the app, and you can request full
        account deletion by contacting us; we will delete or de-identify your data within 30 days
        except where the law requires longer retention.
      </Section>

      <Section heading="Security">
        Data is encrypted in transit; vault items you choose to encrypt are encrypted client-side
        with AES-256-GCM before upload. Access to your records is enforced with row-level security
        at the database layer. No system is perfectly secure — please use a strong, unique
        password.
      </Section>

      <Section heading="Your rights">
        Depending on where you live, you may have rights to access, correct, export, or delete
        your personal information and to object to certain processing. Exercise them in-app (data
        export lives in the family interface) or by contacting us; we respond within the timelines
        your local law requires.
      </Section>

      <Section heading="Children">
        EverAfter is not directed to children under 13 (or the higher minimum age of your
        jurisdiction), and we do not knowingly collect their personal information. Family-tree
        entries about minors are added and controlled by the adult account holder.
      </Section>

      <Section heading="Changes and contact">
        We will post any material changes here and update the date above. Questions or requests:
        {' '}<a className="text-teal-400 underline hover:text-teal-300" href="mailto:wiseandsavvyllc@gmail.com">wiseandsavvyllc@gmail.com</a>.
      </Section>
    </LegalPage>
  );
}

export function LegalPage({ title, icon, updated, children }: { title: string; icon: React.ReactNode; updated: string; children: React.ReactNode }) {
  return (
    <div className="min-h-[100dvh] bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-slate-300">
      <div className="mx-auto max-w-3xl px-4 py-10 sm:py-14">
        <Link to="/" className="mb-8 inline-flex items-center gap-2 text-sm text-slate-400 transition-colors hover:text-white">
          <ArrowLeft className="h-4 w-4" /> Back to EverAfter
        </Link>
        <div className="mb-2 flex items-center gap-3">
          {icon}
          <h1 className="text-3xl font-light text-white">{title}</h1>
        </div>
        <p className="mb-10 text-sm text-slate-500">Last updated: {updated}</p>
        <div className="space-y-8 leading-relaxed">{children}</div>
      </div>
    </div>
  );
}

export function Section({ heading, children }: { heading: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="mb-3 text-lg font-medium text-white">{heading}</h2>
      <div className="text-sm text-slate-400">{children}</div>
    </section>
  );
}
